"use client";

import { ShaderLabComposition, type ShaderLabConfig } from "@basementstudio/shader-lab";

const config: ShaderLabConfig = {
  layers: [
    {
      blendMode: "normal",
      compositeMode: "filter",
      maskConfig: {
        invert: false,
        mode: "multiply",
        source: "luminance",
      },
      hue: 0,
      id: "8f621e7b-a310-46d7-a2ed-6c015473d2bc",
      kind: "effect",
      name: "CRT",
      opacity: 1,
      params: {
        crtMode: "slot-mask",
        cellSize: 5,
        scanlineIntensity: 0.17,
        maskIntensity: 1,
        barrelDistortion: 0,
        chromaticAberration: 2,
        beamFocus: 0.4,
        brightness: 1.2,
        highlightDrive: 1,
        highlightThreshold: 0.62,
        shoulder: 0.25,
        chromaRetention: 1.15,
        shadowLift: 0.16,
        persistence: 0.18,
        vignetteIntensity: 0.62,
        flickerIntensity: 0.2,
        glitchIntensity: 0.13,
        glitchSpeed: 5,
        signalArtifacts: 0.45,
        bloomEnabled: true,
        bloomIntensity: 1.93,
        bloomThreshold: 0,
        bloomRadius: 24,
        bloomSoftness: 0.2,
      },
      saturation: 1,
      type: "crt",
      visible: true,
    },
    {
      blendMode: "normal",
      compositeMode: "filter",
      maskConfig: {
        invert: false,
        mode: "multiply",
        source: "luminance",
      },
      hue: 0,
      id: "6bfa2084-cf57-4f8a-bb49-57cfa1c74b1c",
      kind: "effect",
      name: "Dithering",
      opacity: 1,
      params: {
        preset: "custom",
        algorithm: "bayer-4x4",
        colorMode: "source",
        monoColor: "#f5f5f0",
        shadowColor: "#101010",
        highlightColor: "#f5f2e8",
        pixelSize: 2,
        spread: 0.5,
        levels: 2,
        dotScale: 1,
        animateDither: false,
        ditherSpeed: 1,
        chromaticSplit: false,
      },
      saturation: 1.05,
      type: "dithering",
      visible: true,
    },
    {
      blendMode: "normal",
      compositeMode: "filter",
      maskConfig: {
        invert: false,
        mode: "multiply",
        source: "luminance",
      },
      hue: 0,
      id: "99109d60-a6ce-44a8-9832-24905d6c14bb",
      kind: "effect",
      name: "Pattern",
      opacity: 1,
      params: {
        cellSize: 8,
        preset: "bars",
        colorMode: "source",
        monoColor: "#f5f5f0",
        bgOpacity: 0.16,
        invert: false,
        customColorCount: 4,
        customLuminanceBias: 0,
        customBgColor: "#F5F5F0",
        customColor1: "#0d1014",
        customColor2: "#4d5057",
        customColor3: "#969aa2",
        customColor4: "#e1e2de",
        bloomEnabled: true,
        bloomIntensity: 8,
        bloomThreshold: 0.03,
        bloomRadius: 9.5,
        bloomSoftness: 0.79,
      },
      saturation: 1,
      type: "pattern",
      visible: false,
    },
    {
      blendMode: "multiply",
      compositeMode: "filter",
      maskConfig: {
        invert: false,
        mode: "multiply",
        source: "luminance",
      },
      hue: 0,
      id: "eacfa38c-3321-41f4-856f-acd68d70e1b7",
      kind: "source",
      name: "Image",
      opacity: 0.55,
      params: {
        fitMode: "cover",
        scale: 1.59,
        offset: [0.09000000000000008, 0.030000000000000027],
        svgRasterResolution: "2048",
      },
      saturation: 0.04,
      type: "image",
      visible: true,
      asset: {
        fileName: "images.jpeg",
        kind: "image",
        src: "/images.jpeg",
      },
    },
    {
      blendMode: "normal",
      compositeMode: "filter",
      maskConfig: {
        invert: false,
        mode: "multiply",
        source: "luminance",
      },
      hue: 0,
      id: "a924d323-7026-4b54-8738-355ef0d17009",
      kind: "source",
      name: "Gradient",
      opacity: 1,
      params: {
        preset: "neon-glow",
        activePoints: 2,
        point1Color: "#9F7F2C",
        point1Position: [0, 0],
        point1Weight: 1.31,
        point2Color: "#FF0051",
        point2Position: [0.22999999999999998, 1.12],
        point2Weight: 1.3,
        point3Color: "#662626",
        point3Position: [0.8, 0.3],
        point3Weight: 1.1,
        point4Color: "#220033",
        point4Position: [0.2, -0.8],
        point4Weight: 0.9,
        point5Color: "#1a0a2e",
        point5Position: [-0.5, 0.7],
        point5Weight: 1,
        noiseType: "voronoi",
        noiseSeed: 93.1,
        warpAmount: 0.3,
        warpScale: 3,
        warpIterations: 3,
        warpDecay: 1,
        warpBias: 0.35,
        vortexAmount: -0.25,
        animate: true,
        motionAmount: 0.81,
        motionSpeed: 2,
        falloff: 3.5,
        tonemapMode: "totos",
        glowStrength: 0,
        glowThreshold: 0,
        grainAmount: 0,
        vignetteStrength: 0.1,
        vignetteRadius: 1.5,
        vignetteSoftness: 1,
      },
      saturation: 1.15,
      type: "gradient",
      visible: true,
    },
  ],
  timeline: {
    duration: 8,
    loop: true,
    tracks: [],
  },
};

export function ShaderBackground() {
  return (
    <div className="absolute inset-0 w-full h-full">
      <ShaderLabComposition config={config} />
    </div>
  );
}
